Repository eclipse/winery, pull requests merged in 2018-09, with the labels that each got.

#260 Automated allocation of components to target environments
  CHANGELOG.md
  docs/user/TargetAllocation.md
  docs/user/index.md
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/model/tosca/utils/ModelUtilitiesTest.java
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/utils/ModelUtilities.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/ServiceTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/topologytemplates/TopologyTemplateResource.java
  org.eclipse.winery.repository.rest/src/test/resources/servicetemplates/ServiceTemplateResource-getInjectionOptions-DriverInjectionTest.json
  org.eclipse.winery.repository.rest/src/test/resources/servicetemplates/ServiceTemplateResource-getInjectionOptions.json
  org.eclipse.winery.repository.ui/src/app/section/entityContainer/entity.component.html
  org.eclipse.winery.repository.ui/src/app/section/entityContainer/entity.component.ts
  org.eclipse.winery.repository.ui/src/app/section/section.module.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/policySelection/policySelection.component.html
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/policySelection/policySelection.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/policySelection/policySelection.module.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/request.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/targetAllocation.component.html
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/targetAllocation.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/targetAllocation.module.ts
  org.eclipse.winery.repository.ui/src/app/wineryTargetAllocation/targetAllocation.service.ts
  org.eclipse.winery.repository.ui/src/assets/img/entityBox/targetAllocationButton.png
  org.eclipse.winery.repository.ui/src/css/wineryRepository.css
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/BackendUtils.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/exceptions/AllocationException.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/splitting/InjectRemoval.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/splitting/ProviderRepository.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/splitting/Splitting.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/Allocation.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/Criteria.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/CriteriaCached.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/CriteriaCommon.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/FulfillPolicies.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/PoliciesFilter.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/PolicyComparison.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/PolicyWrapper.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/SplitByIds.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/ConnectsToGraph.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/KargerMinCutVariation.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/MinExternalConnections.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/minhosts/MinHosts.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/criteria/minhosts/TargetLabelAssignment.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/util/AllocationRequest.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/util/AllocationUtils.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/util/FragmentsCache.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/util/PermutationHelper.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/targetallocation/util/TopologyWrapper.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/criteria/fulfillpolicies/FulfillPoliciesTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/ConnectsToGraphTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/KargerMinCutVariationTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/criteria/minexternalconnections/MinExternalConnectionsTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/criteria/minhosts/MinHostsTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/util/AllocationUtilsTest.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/targetallocation/util/TopologyWrapperTest.java
Labels: awaiting-cq-approval

#356 Feature/substitution
  org.eclipse.winery.common/src/main/java/org/eclipse/winery/common/interfaces/IWineryRepositoryCommon.java
  org.eclipse.winery.common/src/main/java/org/eclipse/winery/common/version/VersionUtils.java
  org.eclipse.winery.common/src/test/java/org/eclipse/winery/common/VersionUtilsTest.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/checking/ServiceTemplateComplianceRuleRuleChecker.java
  org.eclipse.winery.model.substitution/pom.xml
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/FindFirstSubstitutionStrategy.java
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/NamespaceSubstitutionStrategy.java
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/Substitution.java
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/SubstitutionStrategy.java
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/SubstitutionUtils.java
  org.eclipse.winery.model.substitution/src/main/java/org/eclipse/winery/model/substitution/Subtypes.java
  org.eclipse.winery.model.substitution/src/test/java/org/eclipse/winery/model/substitution/SubstitutionTestWithGitBackedRepository.java
  org.eclipse.winery.model.substitution/src/test/java/org/eclipse/winery/model/substitution/SubstitutionUtilsTest.java
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TTopologyTemplate.java
  org.eclipse.winery.repository.rest/pom.xml
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/ServiceTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/topologytemplates/TopologyTemplateResource.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/BackendUtils.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/filebased/GitBasedRepository.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/resources/entitytemplates/artifacttemplates/ArtifactTemplateResource.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/splitting/Splitting.java
  org.eclipse.winery.topologymodeler.ui/src/app/canvas/canvas.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/buttonsState.model.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/serviceTemplateId.ts
  org.eclipse.winery.topologymodeler.ui/src/app/navbar/navbar.component.html
  org.eclipse.winery.topologymodeler.ui/src/app/navbar/navbar.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/node/node.component.html
  org.eclipse.winery.topologymodeler.ui/src/app/node/node.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/redux/actions/topologyRenderer.actions.ts
  org.eclipse.winery.topologymodeler.ui/src/app/redux/reducers/topologyRenderer.reducer.ts
  org.eclipse.winery.topologymodeler.ui/src/app/redux/store/winery.store.ts
  org.eclipse.winery.topologymodeler.ui/src/app/services/backend.service.ts
  org.eclipse.winery.topologymodeler.ui/src/app/services/import-topology.service.ts
  pom.xml
Labels: needs review

#368 Update Versions to fix Vulnerabilities
  org.eclipse.winery.repository.ui/package-lock.json
  org.eclipse.winery.repository.ui/package.json
  org.eclipse.winery.repository.ui/src/app/instance/sharedComponents/artifactSource/source.component.css
  org.eclipse.winery.topologymodeler.ui/TmDependencyTestApp/package.json
  org.eclipse.winery.topologymodeler.ui/package-lock.json
  org.eclipse.winery.topologymodeler.ui/package.json
  org.eclipse.winery.topologymodeler.ui/src/app/sidebar/sidebar.component.ts
  org.eclipse.winery.workflowmodeler/package-lock.json
  org.eclipse.winery.workflowmodeler/package.json
  pom.xml
Labels: in progress

#369 Fix ID Generation For RelationshipTemplates
  org.eclipse.winery.topologymodeler.ui/src/app/canvas/canvas.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/topologyModelerConfiguration.ts
Labels: needs review, topology modeler
