Repository eclipse/winery, pull requests merged in 2018-07, with the labels that each got.

#245 Fix testwineryrepositoryclient
  org.eclipse.winery.common/src/main/java/org/eclipse/winery/common/interfaces/IWineryRepository.java
  org.eclipse.winery.repository.client/pom.xml
  org.eclipse.winery.repository.client/src/main/java/org/eclipse/winery/repository/client/WineryRepositoryClient.java
  org.eclipse.winery.repository.client/src/test/java/org/eclipse/winery/repository/client/TestWineryRepositoryClient.java
  org.eclipse.winery.repository.rest/pom.xml
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/RestUtils.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/_support/AbstractComponentsResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/entitytypes/artifacttypes/ArtifactTypeResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/ServiceTemplatesResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/plans/PlansResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/selfserviceportal/OptionsResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/server/WineryUsingHttpServer.java
Labels: needs review

#288 Create FAQ.md
  docs/user/FAQ.md
  docs/user/index.md
Labels: needs review

#231 add functionality to add and save property constraints
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/apiData/boundarydefinitions/PropertyConstraintsApiData.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/entitytemplates/TEntityTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/entitytemplates/artifacttemplates/ArtifactTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/entitytemplates/policytemplates/PolicyTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/boundarydefinitions/BoundaryDefinitionsResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/boundarydefinitions/PropertyConstraintsResource.java
  org.eclipse.winery.repository.rest/src/test/java/org/eclipse/winery/repository/rest/resources/servicetemplates/boundarydefinitions/propertyconstraints/PropertyConstraintsResourceTest.java
  org.eclipse.winery.repository.ui/src/app/instance/instance.service.ts
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/boundaryDefinitions/boundaryDefinitions.module.ts
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/boundaryDefinitions/propertyConstraints/propertyConstraints.component.html
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/boundaryDefinitions/propertyConstraints/propertyConstraints.component.ts
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/boundaryDefinitions/propertyConstraints/propertyConstraints.service.ts
  org.eclipse.winery.repository.ui/src/app/wineryMainModules/artictTemplates/artifactTemplateRouter.module.ts
  org.eclipse.winery.repository.ui/src/app/wineryMainModules/policyTemplates/policyTemplateRouter.module.ts
Labels: needs review

#291 Ignore extracted orion editor
  .gitignore
Labels: needs review

#294 Fix/compare to
  org.eclipse.winery.topologymodeler.ui/src/app/canvas/entities-modal/modal-model.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/ttopology-template.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/utils.ts
  org.eclipse.winery.topologymodeler.ui/src/app/navbar/navbar.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/services/backend.service.ts
  org.eclipse.winery.topologymodeler.ui/src/app/winery.component.ts
Labels: needs review

#292 Clean up comments in TDeploymentArtifact
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TDeploymentArtifact.java
Labels: needs review

#296 Refine QuickStart for Windows
  docs/user/quickstart.md
Labels: in progress

#297 Add tags to Node Types
  org.eclipse.winery.repository.ui/src/app/instance/instance.service.ts
  org.eclipse.winery.repository.ui/src/app/wineryMainModules/nodeTypes/nodeType.module.ts
  org.eclipse.winery.repository.ui/src/app/wineryMainModules/nodeTypes/nodeTypeRouter.module.ts
Labels: in progress

#298 Removes JAX-B comments at TBoundaryDefinitions
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TBoundaryDefinitions.java
Labels: in progress

#299 Add documentation on how to enable TOSCA XSD validation at Winery
  docs/dev/config/IntelliJ IDEA/README.md
Labels: in progress

#300 Disable WADL generation
  org.eclipse.winery.repository.rest/src/main/webapp/WEB-INF/web.xml
Labels: needs review

#303 Add checklist for NOTICE file
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#302 Update Notice file
  NOTICE
Labels: needs review

#304 Fix inital open palette in topology modeler
  org.eclipse.winery.topologymodeler.ui/src/app/redux/reducers/winery.reducer.ts
Labels: needs review

#301 fix modal for entering input and output parameters for plans
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/plans/plans.component.html
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/plans/plans.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryIoParameter/wineryIoParameter.component.html
  org.eclipse.winery.repository.ui/src/app/wineryIoParameter/wineryIoParameter.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryModalModule/winery.modal.component.html
  org.eclipse.winery.repository.ui/src/app/wineryModalModule/winery.modal.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryModalModule/winery.modal.module.ts
Labels: in progress

#312 Add missing tests
  org.eclipse.winery.common/pom.xml
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TArtifactReference.java
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TServiceTemplate.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyChecker.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyErrorLogger.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/consistencycheck/ElementErrorList.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyCheckerTest.java
  pom.xml
Labels: in progress

#315 fix files
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/RestUtils.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/entitytemplates/artifacttemplates/ArtifactTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/selfserviceportal/SelfServicePortalResource.java
  org.eclipse.winery.repository.rest/src/test/java/org/eclipse/winery/repository/rest/resources/entitytemplates/artifacttemplates/ArtifactTemplateResourceTest.java
  org.eclipse.winery.repository.ui/src/app/instance/artifactTemplates/filesTag/files.service..ts
  org.eclipse.winery.repository.ui/src/app/instance/sharedComponents/artifactSource/source.component.html
  org.eclipse.winery.repository.ui/src/app/instance/sharedComponents/artifactSource/source.service.ts
  org.eclipse.winery.repository.ui/src/app/wineryEditorModule/wineryEditor.component.ts
Labels: needs review

#320 Pins the save button to the color selector
  org.eclipse.winery.repository.ui/src/app/instance/sharedComponents/visualAppearance/visualAppearance.component.css
  org.eclipse.winery.repository.ui/src/app/instance/sharedComponents/visualAppearance/visualAppearance.component.html
Labels: needs review

#318 Streamline Prefs.xml
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/Prefs.java
Labels: needs review

#326 fix loading of all elements
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/IGenericRepository.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/backend/IGenericRepositoryTest.java
Labels: in progress

#329 Adds size check and improves progress display
  org.eclipse.winery.cli/src/main/java/org/eclipse/winery/cli/WineryCli.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyChecker.java
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyCheckerConfiguration.java
  org.eclipse.winery.repository/src/test/java/org/eclipse/winery/repository/backend/consistencycheck/ConsistencyCheckerTest.java
Labels: in progress

#330 Add -cb command line option and fix Copybara generator for 0 byte files
  org.eclipse.winery.cli/pom.xml
  org.eclipse.winery.cli/src/main/java/org/eclipse/winery/cli/WineryCli.java
  org.eclipse.winery.tools.copybaragenerator/src/main/java/org/eclipse/winery/tools/copybaragenerator/CopybaraGenerator.java
Labels: in progress

#331 fix importing a topology into an empty topology
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/backend/BackendUtils.java
Labels: in progress

#335 Add Co-authored-by-hint
  docs/dev/ToolChain.md
Labels: in progress

#334 Add README.md and LICENSE to copybara generation
  .gitignore
  org.eclipse.winery.cli/src/main/java/org/eclipse/winery/cli/WineryCli.java
  org.eclipse.winery.tools.copybaragenerator/src/main/java/org/eclipse/winery/tools/copybaragenerator/CopybaraGenerator.java
  org.eclipse.winery.tools.copybaragenerator/src/test/java/org/eclipse/winery/tools/copybaragenerator/CopybaraGeneratorTest.java
Labels: needs review

#333 versioning fixes
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/topologyTemplate/topologyTemplate.component.html
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/topologyTemplate/topologyTemplate.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryRepository.html
  org.eclipse.winery.repository.ui/src/app/wineryVersionModule/wineryVersion.component.html
  org.eclipse.winery.repository.ui/src/app/wineryVersionModule/wineryVersion.component.ts
Labels: in progress

#337 Fix CORS problem
  org.eclipse.winery.repository.ui/src/app/wineryUploader/wineryUploader.component.ts
Labels: in progress

#338 add all split and matched service templates as component versions
  org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/splitting/Splitting.java
Labels: in progress

#281 complete feature compliance checking and add documentation
  docs/user/ComplianceChecking.md
  docs/user/graphics/compliance-checking/complianceRule.PNG
  docs/user/graphics/compliance-checking/complianceRuleDetection.PNG
  docs/user/graphics/compliance-checking/createComplianceRule.PNG
  docs/user/graphics/compliance-checking/identifier_modeler.PNG
  docs/user/graphics/compliance-checking/required-structure.PNG
  docs/user/graphics/compliance-checking/satisfied-topology.PNG
  docs/user/graphics/compliance-checking/satisfied.PNG
  docs/user/graphics/compliance-checking/step2.PNG
  docs/user/graphics/compliance-checking/unsatisfied-topology.PNG
  docs/user/graphics/compliance-checking/unsatisfied.PNG
  docs/user/index.md
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/checking/ComplianceRuleChecker.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/checking/ServiceTemplateCheckingResult.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/checking/ServiceTemplateComplianceRuleRuleChecker.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/IToscaMatcher.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/TOSCAComplianceRuleMatcher.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/ToscaComparatorProxy.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/ToscaComplianceRuleMatcher.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/ToscaDefaultMatcher.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/matching/ToscaIsomorphismMatcher.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/model/ToscaEdge.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/model/ToscaEdgeFactory.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/model/ToscaEntity.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/model/ToscaGraph.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/model/ToscaNode.java
  org.eclipse.winery.compliance/src/main/java/org/eclipse/winery/compliance/transformation/ToscaTransformer.java
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/compliance/TOSCAGraphIsomorphismTest.java
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/compliance/TOSCAModelHelper.java
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/compliance/ToscaGraphIsomorphismTest.java
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/compliance/ToscaModelHelper.java
  org.eclipse.winery.compliance/src/test/java/org/eclipse/winery/compliance/ToscaModelPropertiesBuilder.java
  org.eclipse.winery.model.tosca/src/main/java/org/eclipse/winery/model/tosca/TServiceTemplate.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/compliancerules/CRTopologyTemplateResource.java
  org.eclipse.winery.repository.rest/src/main/java/org/eclipse/winery/repository/rest/resources/servicetemplates/ServiceTemplateResource.java
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/constraintChecking/constraintChecking.service.ts
  org.eclipse.winery.repository.ui/src/app/instance/serviceTemplates/topologyTemplate/topologyTemplate.component.ts
  org.eclipse.winery.repository.ui/src/app/wineryUtils/utils.ts
  org.eclipse.winery.topologymodeler.ui/src/app/canvas/entities-modal/entities-modal.service.ts
  org.eclipse.winery.topologymodeler.ui/src/app/models/topologyModelerConfiguration.ts
  org.eclipse.winery.topologymodeler.ui/src/app/navbar/navbar.component.ts
  org.eclipse.winery.topologymodeler.ui/src/app/services/backend.service.ts
  org.eclipse.winery.topologymodeler.ui/src/app/winery-alert/winery-alert.service.ts
Labels: awaiting-cq-approval
